from turtle import *
import time
pensize(5)
pencolor("red")
fillcolor("pink")
hideturtle()
begin_fill()
left(135)
forward(100)
circle(-50,180)
left(90)
circle(-50,180)
forward(100)
end_fill()
penup()
goto(0,80)
pendown()
pencolor("yellow")
write("Marry Christmas!",align = "center",font = ("Arial",15,"bold"))
time.sleep(3)
penup()
goto(0,-200)
pendown()
pencolor("purple")
write("Can you be my gf?",align = "center",font = ("Arial",20,"bold"))
time.sleep(3)